# Generated by Django 3.2.8 on 2021-12-03 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='credential',
            fields=[
                ('cred_id', models.IntegerField(default='', editable=False, primary_key=True, serialize=False, unique=True)),
                ('abbreviation', models.CharField(max_length=20, verbose_name='Abbreviation')),
            ],
            options={
                'verbose_name': 'Credential',
                'db_table': 'credentials',
            },
        ),
        migrations.CreateModel(
            name='drug',
            fields=[
                ('drugid', models.IntegerField(default='', editable=False, primary_key=True, serialize=False, unique=True)),
                ('drugname', models.CharField(default='', max_length=30, unique=True, verbose_name='Drug Name')),
                ('isopioid', models.BooleanField(verbose_name='Is Opioid')),
            ],
            options={
                'verbose_name': 'Drug',
                'db_table': 'pd_drugs',
            },
        ),
        migrations.CreateModel(
            name='prescriber',
            fields=[
                ('npi', models.IntegerField(default='', editable=False, primary_key=True, serialize=False, unique=True)),
                ('fname', models.CharField(max_length=11, verbose_name='First Name')),
                ('lname', models.CharField(max_length=11, verbose_name='Last Name')),
                ('gender', models.CharField(max_length=1, verbose_name='Gender')),
                ('state', models.CharField(max_length=2, verbose_name='First Name')),
                ('specialty', models.CharField(max_length=62, verbose_name='Specialty')),
                ('isopioidprescriber', models.BooleanField(verbose_name='Is Opioid Prescriber')),
            ],
            options={
                'verbose_name': 'Prescriber',
                'db_table': 'pd_prescriber',
            },
        ),
        migrations.CreateModel(
            name='state',
            fields=[
                ('state', models.CharField(default='', max_length=14, primary_key=True, serialize=False, verbose_name='State')),
                ('stateabbrev', models.CharField(max_length=2, verbose_name='State Abbreviation')),
                ('population', models.IntegerField(verbose_name='Population')),
                ('deaths', models.IntegerField(verbose_name='Deaths')),
            ],
            options={
                'verbose_name': 'State',
                'db_table': 'pd_statedata',
            },
        ),
        migrations.CreateModel(
            name='triple',
            fields=[
                ('npi', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='titan.prescriber', verbose_name='Prescriber')),
                ('qty', models.IntegerField()),
                ('drugname', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='titan.drug', verbose_name='DrugName')),
            ],
            options={
                'verbose_name': 'Triple',
                'db_table': 'pd_triple',
                'unique_together': {('npi', 'drugname')},
            },
        ),
        migrations.CreateModel(
            name='link',
            fields=[
                ('npi', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='titan.prescriber', verbose_name='NPI')),
                ('cred_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='titan.credential', verbose_name='Credential_id')),
            ],
            options={
                'verbose_name': 'Prescriber_Credential',
                'db_table': 'linking',
                'unique_together': {('npi', 'cred_id')},
            },
        ),
    ]
